actor_hidden_sizes:
- 512
- 256
alpha: 0.1
alpha_lr: 0.0003
alpha_tuning: true
buffer_alpha: 0.7
buffer_beta: 0.5
buffer_beta_increment: 0.001
buffer_decay_steps: 100000
buffer_type: ER
checkpoint: ../final_checkpoints/01-30-sac-foundation/checkpoint_best.pth
critic_hidden_sizes:
- 512
- 256
- 64
discount: 0.98
env_id: 0
epochs: 10
eval_episodes: 20
eval_freq: 50
log_std_max: 2
log_std_min: -20
memory_size: 1000000
mutation_config:
  enabled: false
  maxs:
  - 0.1
  - 256
  - 100000
  means:
  - 0
  - 0
  - 0
  mins:
  - 1.0e-06
  - 16
  - 1000
  parameters:
  - learning_rate
  - batch_size
  - memory_size
  prob:
  - 0.3
  - 0.3
  - 0.3
  vars:
  - 0.1
  - 0.1
  - 0.1
name: BasicOpponent
num_runs: 1
opponent_names:
- undefined
specialized_config:
  _dtype: None
  device: cuda
  do_render: null
  max_memory_size: null
  num_episodes: null
tau: 0.005
trainer_config:
  batch_size: 512
  beta1: 0.9
  beta2: 0.999
  checkpoint_dir: C:\Users\Arb01351\Documents\GitHub\Reinforce-the-Puck\models\checkpoints
  epochs: 100
  id: -1
  learning_rate: 0.001
  learning_rate_actor: 0.0003
  learning_rate_critic: 0.0003
  log_freq: 10
  log_name: sac_multi
  max_checkpoints: 5
  save_checkpoint_freq: 100
type: sac
update_target_every: 100
version: 1
