actor_hidden_sizes:
- 512
- 256
buffer_alpha: 0.6
buffer_beta: 0.4
buffer_beta_increment: 0.001
buffer_decay_steps: 1000000
buffer_type: ER
checkpoint: null
critic_hidden_sizes:
- 512
- 256
- 64
discount: 0.98
env_id: 2
epochs: 10
eps: 1
eval_episodes: 20
eval_freq: 50
memory_size: 1000000
mutation_config:
  enabled: false
  maxs:
  - 0.1
  - 256
  - 100000
  means:
  - 0
  - 0
  - 0
  mins:
  - 1.0e-06
  - 16
  - 1000
  parameters:
  - learning_rate
  - batch_size
  - memory_size
  prob:
  - 0.3
  - 0.3
  - 0.3
  vars:
  - 0.1
  - 0.1
  - 0.1
name: BasicOpponent
noise_beta: 0.5
noise_clip: 0.5
noise_sigma: 0.1
num_runs: 1
opponent_names:
- opponent3
- opponent4
- opponent5
- opponent1
- opponent2
policy_delay: 2
specialized_config:
  _dtype: torch.float32
  device: cuda
  do_render: false
  max_memory_size: 100000
  num_episodes: 60000
tao: 0.005
trainer_config:
  batch_size: 256
  beta1: 0.9
  beta2: 0.999
  checkpoint_dir: /home/tomf/projects/WiSe24_25/Reinforce-the-Puck/models/checkpoints
  epochs: 100
  id: -1
  learning_rate: 0.001
  learning_rate_actor: 3.0e-05
  learning_rate_critic: 3.0e-05
  log_freq: 10
  log_name: noise_eval_foundation/td3-blue
  max_checkpoints: 5
  save_checkpoint_freq: 100
type: td3
update_target_every: -1
use_target_net: true
version: 1
