# Please refer to the documentation for more information on the configuration file.

base_config:
  dtype: float32
  num_episodes: 1

env1:
  env_name: Pendulum-v1
  env_type: gym
  id: 0
  max_steps: 1000

env2:
  env_name: MountainCarContinuous-v0
  env_type: gym
  id: 1
  max_steps: 1000

agent1:
  type: ddpg
  env_id: 0
  num_runs: 1
  mutation_config:
    enabled: false
    means: []
    vars: []
    prob: []
    parameters: []
  trainer_config:
    learning_rate: 0.001
    log_name: agent_ddpg
    batch_size: 64
  specialized_config:
    num_episodes: 2 # This will override the num_episodes in the base_config
