# Please refer to the documentation for more information on the configuration file.

base_config:
  dtype: float32
  num_episodes: 1

agent1:
  type: ddpg
  trainer_config:
    learning_rate: 0.001
    log_name: agent1
    batch_size: 64
  specialized_config:
    num_episodes: 3 # This will override the num_episodes in the base_config

agent2:
  type: ddpg
  trainer_config:
    learning_rate: 0.0001
    log_name: agent2
    batch_size: 64


agent3:
  type: ddpg
  trainer_config:
    learning_rate: 0.0001
    log_name: agent3
    batch_size: 64
