# Please refer to the documentation for more information on the configuration file.

base_config:
  dtype: float32
  num_episodes: 2500
  do_render: true

env1:
  env_name: Hockey-v0
  env_type: gym
  id: 0
  max_steps: 1000

  train_both: False
  train_all: False
  new_agents_after_eval: 3
  do_render: False

agent1:
  type: moe
  opponent_names: ["opponent1", "opponent2", "opponent3", "opponent4"]
  env_id: 0
  memory_size: 100000
  buffer_type: BER
  agent_a_path: "../final_checkpoints/11-02-sac-ft/checkpoint_best.pth"
  agent_a_type: "sac"
  agent_b_path: "../final_checkpoints/08-02-td3-ft-catch_bonus/checkpoint_last.pth"
  agent_b_type: "td3"

  gamma: 0.99
  hidden_size: [512, 512]

  trainer_config:
    learning_rate: 0.003
    log_name: mue_hockey
    batch_size: 512

opponent1:
  type: "basic_opponent_strong"

opponent2:
  type: td3
  checkpoint: "../final_checkpoints/08-02-td3-ft/checkpoint_best.pth"
  actor_hidden_sizes: [516, 256]
  critic_hidden_sizes: [1024, 516, 256, 128]

opponent3:
  type: sac
  checkpoint: "../final_checkpoints/08-02-sac-ft/checkpoint_best.pth"
  actor_hidden_sizes: [512, 256]
  critic_hidden_sizes: [512, 256, 64]

opponent4:
  type: td3
  checkpoint: "../final_checkpoints/08-02-td3-ft-catch_bonus/checkpoint_last.pth"
  actor_hidden_sizes: [516, 256]
  critic_hidden_sizes: [1024, 516, 256, 128]

opponent5:
  type: sac
  checkpoint: "../final_checkpoints/11-02-sac-ft/checkpoint_best.pth"
  actor_hidden_sizes: [512, 256]
  critic_hidden_sizes: [512, 256, 64]
