# Please refer to the documentation for more information on the configuration file.

base_config:
  dtype: float32
  num_episodes: 800
  do_render: true

env1:
  env_name: Hockey-v0
  env_type: gym
  id: 0
  max_steps: 1000


agent1:
  type: sac
  env_id: 0
  tau: 0.005 # Target network update rate (Soft update)
  memory_size: 1000000
  discount: 0.98 # Discount factor
  alpha: 0.1 # Entropy regularization coefficient
  alpha_lr: 0.0003 # Learning rate for alpha
  log_std_min: -20 #lower bound for log_std
  log_std_max: 2 #upper bound for log_std
  actor_hidden_sizes: [512, 256]
  critic_hidden_sizes: [512, 256, 64]
  alpha_tuning: True
  trainer_config:
    #learning_rate_actor: 0.0003
    learning_rate_actor: 0.0006
    #learning_rate_critic: 0.0003
    learning_rate_critic: 0.0006
    log_name: agent_sac_hokey
    batch_size: 256
