# Please refer to the documentation for more information on the configuration file.

base_config:
  dtype: float32
  num_episodes: 100

env1:
  env_name: Pendulum-v1
  env_type: gym
  id: 0
  max_steps: 1000

env2:
  env_name: MountainCarContinuous-v0
  env_type: gym
  id: 1
  max_steps: 1000

agent1:
  type: sac
  env_id: 0
  tau: 0.001 # Target network update rate (Soft update)
  memory_size: 100000
  discount: 0.97 # Discount factor
  alpha: 0.02 # Entropy regularization (inital value -> alpha tuning)
  alpha_lr: 0.0003 # Learning rate for alpha
  log_std_min: -20 #lower bound for log_std
  log_std_max: 2 #upper bound for log_std
  actor_hidden_sizes: [128, 128]
  critic_hidden_sizes: [128, 128, 64]
  alpha_tuning: True
  trainer_config:
    learning_rate_actor: 0.0005
    learning_rate_critic: 0.00001
    log_name: agent_sac
    batch_size: 64
  specialized_config:
    num_episodes: 1000
