# Please refer to the documentation for more information on the configuration file.

base_config:
  dtype: float32
  num_episodes: 1000

env1:
  env_name: Pendulum-v1
  id: 0
  max_steps: 1000

env2:
  env_name: LunarLander-v3
  id: 1
  max_steps: 1000

env3:
  env_name: Hockey-v0
  env_type: gym
  id: 2
  mode: 0 # 0: normal, 1: shooting, 2: defense
  max_steps: 1000
  start_training_after_steps: 0
  # train_both: False # TODO: Implement this
  do_render: True

agent1:
  type: td3
  checkpoint: Hockey-v0/td3/td3_not_cross_hockey_2025-01-28_09-26-13_100/checkpoint_last.pth
  opponent_name: "opponent2"
  env_id: 2
  eps: 1
  eval_freq: 10
  eval_episodes: 20
  discount: 0.99
  actor_hidden_sizes: [516, 256]
  critic_hidden_sizes: [1024, 516, 256, 128]
  policy_delay: 3
  update_target_every: -1
  noise_sigma: 0.2
  noise_clip: 0.8
  noise_beta: 1.0 # Pink noise
  memory_size: 1000000
  # buffer_type: BPER # Balanced Prioritized Experience Replay
  buffer_type: ER
  num_runs: 1
  mutation_config:
    enabled: false
  trainer_config:
    learning_rate_actor: 0.0003
    learning_rate_critic: 0.0003
    log_name: td3_hockey_train_sac
    batch_size: 256
  specialized_config:
    num_episodes: 10000
    do_render: False

opponent1:
  type: "basic_opponent_strong"
  trainer_config:
    learning_rate_actor: 0.0007
    learning_rate_critic: 0.0003

opponent2:
  type: sac
  opponent_name: "opponent1"
  checkpoint: "Hockey-v0/sac/best_jona_2025_01_28.pth"
  env_id: 0
  tau: 0.005 # Target network update rate (Soft update)
  memory_size: 1000000
  discount: 0.98 # Discount factor
  alpha: 0.1 # Entropy regularization coefficient
  alpha_lr: 0.0003 # Learning rate for alpha
  log_std_min: -20 #lower bound for log_std
  log_std_max: 2 #upper bound for log_std
  actor_hidden_sizes: [512, 256]
  critic_hidden_sizes: [512, 256, 64]
  alpha_tuning: True
  trainer_config:
    #learning_rate_actor: 0.0003
    learning_rate_actor: 0.0003
    #learning_rate_critic: 0.0003
    learning_rate_critic: 0.0003
    log_name: agent_sac_hokey
    batch_size: 512
