# Please refer to the documentation for more information on the configuration file.

base_config:
  dtype: float32
  num_episodes: 1000

env1:
  env_name: Pendulum-v1
  id: 0
  max_steps: 1000

env2:
  env_name: LunarLander-v3
  id: 1
  max_steps: 1000

agent1:
  type: td3
  checkpoint: null
  env_id: 0
  eps: 1
  discount: 0.95
  actor_hidden_sizes: [128, 128]
  critic_hidden_sizes: [128, 128, 64]
  policy_delay: 3
  update_target_every: -1
  tao: 0.005
  noise_sigma: 0.2
  noise_clip: 0.5
  noise_beta: 1.0 # Pink noise
  memory_size: 100000
  num_runs: 10
  mutation_config:
    enabled: true
    means: [0, 0, 0, 0, 0, 0, 0]
    vars: [0.1, 0.1, 0.3, 0.1, 0.05, 0.1, 0.1]
    maxs: ["inf", "inf", "inf", "inf", 0.99999999, "inf", "inf"]
    mins: [0.00000001, 0.00000001, 16, 0, 0.00000001, 0, 0]
    prob: [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]
    parameters:
      [
        "learning_rate_actor",
        "learning_rate_critic",
        "batch_size",
        "tao",
        "discount",
        "noise_sigma",
        "noise_clip",
      ]
  trainer_config:
    learning_rate_actor: 0.001
    learning_rate_critic: 0.001
    log_name: td3_pendulum
    batch_size: 128
  specialized_config:
    num_episodes: 1

agent2:
  type: td3
  checkpoint: null
  env_id: 1
  eps: 1
  discount: 0.99
  actor_hidden_sizes: [256, 128]
  critic_hidden_sizes: [256, 128, 64]
  policy_delay: 2
  update_target_every: -1
  tao: 0.005
  noise_sigma: 0.2
  noise_clip: 0.5
  noise_beta: 1.0 # Pink noise
  memory_size: 1000000
  num_runs: 5
  mutation_config:
    enabled: true
    means: [0, 0, 0, 0, 0, 0, 0]
    vars: [0.1, 0.1, 0.3, 0.1, 0.05, 0.1, 0.1]
    maxs: ["inf", "inf", "inf", "inf", 0.99999999, "inf", "inf"]
    mins: [0.00000001, 0.00000001, 16, 0, 0.00000001, 0, 0]
    prob: [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]
    parameters:
      [
        "learning_rate_actor",
        "learning_rate_critic",
        "batch_size",
        "tao",
        "discount",
        "noise_sigma",
        "noise_clip",
      ]
  trainer_config:
    learning_rate_actor: 0.0003
    learning_rate_critic: 0.0003
    log_name: td3_luna
    batch_size: 128
  specialized_config:
    num_episodes: 1

agent3:
  type: td3
  checkpoint: null
  env_id: 1
  eps: 1
  discount: 0.99
  actor_hidden_sizes: [128, 64]
  critic_hidden_sizes: [128, 64, 32]
  policy_delay: 2
  update_target_every: -1
  tao: 0.005
  noise_sigma: 0.2
  noise_clip: 0.5
  noise_beta: 1.0 # Pink noise
  memory_size: 1000000
  num_runs: 5
  mutation_config:
    enabled: true
    means: [0, 0, 0, 0, 0, 0, 0]
    vars: [0.1, 0.1, 0.3, 0.1, 0.05, 0.1, 0.1]
    maxs: ["inf", "inf", "inf", "inf", 0.99999999, "inf", "inf"]
    mins: [0.00000001, 0.00000001, 16, 0, 0.00000001, 0, 0]
    prob: [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7]
    parameters:
      [
        "learning_rate_actor",
        "learning_rate_critic",
        "batch_size",
        "tao",
        "discount",
        "noise_sigma",
        "noise_clip",
      ]
  trainer_config:
    learning_rate_actor: 0.0003
    learning_rate_critic: 0.0003
    log_name: td3_luna_smaller
    batch_size: 128
  specialized_config:
    num_episodes: 1
