td3_bper_smaller_buffer_base:
  checkpoint: "models/Hockey-v0/td3/td3_hockey_bper_smaller_buffer_2025-01-30_16-56-17_100/checkpoint_best.pth"
  type: td3
td3_base_long_training:
  checkpoint: "models/Hockey-v0/td3/td3_not_cross_hockey_2025-01-28_09-26-13_100/checkpoint_best.pth"
  type: td3
sac_ft:
  checkpoint: "final_checkpoints/08-02-sac-ft/checkpoint_best.pth"
  type: sac
sac_hierarchical:
  checkpoint: "final_checkpoints/07-02-hierarchical-sac-foundation/checkpoint_best.pth"
  type: sac_hierarchical
td3_bper_100k_new_reward:
  checkpoint: "models/Hockey-v0/td3/bper_100k_new_reward_2025-02-07_23-24-14_100/checkpoint_best.pth"
  type: td3
td3_ft:
  checkpoint: "final_checkpoints/08-02-td3-ft/checkpoint_best.pth"
  type: td3
td3_block_puck:
  checkpoint: "models/Hockey-v0/td3/08-02-td3-foundation-100k-fine-tuned-block-puck2_2025-02-08_12-42-37_100/checkpoint_best.pth"
  type: td3
