sac_foundation:
  checkpoint:  "../final_checkpoints/01-30-sac-foundation/checkpoint_best.pth"
  type: sac

hsac_foundation:
  checkpoint: "../final_checkpoints/07-02-hierarchical-sac-foundation/checkpoint_best.pth"
  type: sac_hierarchical

td3:
  checkpoint: "../final_checkpoints/01-01-td3/td3.pth"
  type: td3
