td3_bper_smaller_buffer_base:
  checkpoint: "models/Hockey-v0/td3/td3_hockey_bper_smaller_buffer_2025-01-30_16-56-17_100/checkpoint_best.pth"
  type: td3
td3_pink_target_noise:
  checkpoint: "models/Hockey-v0/td3/td3_hockey_pink_target_noise_continued_2025-01-30_16-49-23_100/checkpoint_best.pth"
  type: td3
td3_base_long_training:
  checkpoint: "models/Hockey-v0/td3/td3_not_cross_hockey_2025-01-28_09-26-13_100/checkpoint_best.pth"
  type: td3
sac1:
  checkpoint: "models/Hockey-v0/sac/best_jona_2025_01_28.pth"
  type: sac
td3_cross:
  checkpoint: "models/Hockey-v0/td3_cross/td3_cross_hockey_BatchRenorm_new_2025-01-29_20-52-50_100/checkpoint_best.pth"
  type: td3_cross
td3_ber_1k:
  checkpoint: "models/Hockey-v0/td3/ber_100k_2025-02-07_17-31-53_100/checkpoint_best.pth"
  type: td3
td3_ber_1k_new_reward:
  checkpoint: "models/Hockey-v0/td3/ber_100k_new_reward_2025-02-07_23-24-11_100/checkpoint_best.pth"
  type: td3
td3_ber_1mio:
  checkpoint: "models/Hockey-v0/td3/ber_1mio_2025-02-07_17-31-54_100/checkpoint_best.pth"
  type: td3
td3_ber_1mio_new_reward:
  checkpoint: "models/Hockey-v0/td3/ber_1mio_new_reward_2025-02-07_23-24-12_100/checkpoint_best.pth"
  type: td3
td3_bper_100k:
  checkpoint: "models/Hockey-v0/td3/bper_100k_2025-02-07_17-31-55_100/checkpoint_best.pth"
  type: td3
td3_bper_100k_new_reward:
  checkpoint: "models/Hockey-v0/td3/bper_100k_new_reward_2025-02-07_23-24-14_100/checkpoint_best.pth"
  type: td3
