td3-ber:
  checkpoint: "../final_checkpoints/td3-buffers/ber/checkpoint_last.pth"
  type: td3
td3-er:
  checkpoint: "../final_checkpoints/td3-buffers/er/checkpoint_last.pth"
  type: td3
td3-per:
  checkpoint: "../final_checkpoints/td3-buffers/per/checkpoint_last.pth"
  type: td3
td3-white:
  checkpoint: "../final_checkpoints/td3-noise/white/checkpoint_last.pth"
  type: td3
td3-blue:
  checkpoint: "../final_checkpoints/td3-noise/blue/checkpoint_last.pth"
  type: td3
td3-default-reward:
  checkpoint: "../final_checkpoints/rewards/td3-default/checkpoint_last.pth"
  type: td3
sac-default-reward:
  checkpoint: "../final_checkpoints/rewards/sac-default/checkpoint_last.pth"
  type: sac
sac-own:
  checkpoint: "../final_checkpoints/td3-buffers/sac-er/checkpoint_last.pth"
  type: sac

## Others

moe-cross2:
  checkpoint: "../final_checkpoints/moe-cross-2/checkpoint_best.pth"
  type: moe

td3_foundation:
  checkpoint: "../final_checkpoints/08-02-td3-foundation/checkpoint_best.pth"
  type: td3

sac_foundation:
  checkpoint: "../final_checkpoints/01-30-sac-foundation/checkpoint_best.pth"
  type: sac

sac-ft-50k:
  checkpoint: "../final_checkpoints/19-02-sac-ft-50k/checkpoint_best.pth"
  type: sac

moe-v3:
  checkpoint: "../final_checkpoints/20-02-moe-v3/checkpoint_best.pth"
  type: moe

moe-selfplay-expert-training:
  checkpoint: "../final_checkpoints/moe-selfplay-expert-training/checkpoint_best.pth"
  type: moe

moe-expert-train-pretrain:
  checkpoint: "../final_checkpoints/moe-expert-train-pretrain/checkpoint_best.pth"
  type: moe

moe-empty:
  checkpoint: "../final_checkpoints/moe-empty/checkpoint_best.pth"
  type: moe

moe-selfplay:
  checkpoint: "../final_checkpoints/moe-selfplay/checkpoint_best.pth"
  type: moe

sac-selfplay:
  checkpoint: "../final_checkpoints/sac-selfplay/checkpoint_best.pth"
  type: sac

td3-selfplay:
  checkpoint: "../final_checkpoints/td3-selfplay/checkpoint_best.pth"
  type: td3

td3-selfplay2:
  checkpoint: "../final_checkpoints/td3-selfplay2/checkpoint_best.pth"
  type: td3

sac-selfplay-2:
  checkpoint: "../final_checkpoints/sac-selfplay-2/checkpoint_best.pth"
  type: sac
