td3-er:
  checkpoint: "../final_checkpoints/td3-buffers/er/checkpoint_last.pth"
  type: td3
td3-pink:
  checkpoint: "../final_checkpoints/td3-noise/pink/checkpoint_last.pth"
  type: td3
sac-er:
  checkpoint: "../final_checkpoints/td3-buffers/sac-er/checkpoint_last.pth"
  type: sac
sac-default-reward:
  checkpoint: "../final_checkpoints/rewards/sac-default/checkpoint_last.pth"
  type: sac
moe-selfplay-expert-training:
  checkpoint: "../final_checkpoints/moe-selfplay-expert-training/checkpoint_best.pth"
  type: moe
